// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcyjqvgrbhhkganofiou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjeWpxdmdyYmhoa2dhbm9maW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTM2ODcsImV4cCI6MjA1OTA2OTY4N30.2o_MFuAFwB0CkDnt55A6B0URNlaBWEzRxIYkEGSdyhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);